services:
  bot:
    build: 
      dockerfile: docker/Dockerfile.release
    image: guildmaster:2024-03-30
    ports: 
      - 22020:8080
    volumes:
      - .:/code
    environment:
      DB_DSN: "postgres://postgres:postgres@db:5432/guildmaster"
    depends_on:
      - db
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guildmaster
    ports:
      - 22021:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "guildmaster", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: